#!/usr/bin/env python3
"""Writes the layerxanchor genesis section init-chain.sh merges into the Paxeer genesis.

Checkpoint settlement and the guarantor bond are the native layerxanchor module behind the
precompile at 0x0000000000000000000000000000000000001014. Nothing is deployed for them: the
authority, the EVM chain id and settlement contract guarantors sign, the network id, the
certificate threshold, the minimum bond and the sequencer authorization are chain genesis state.

The authority is an account the bring-up already controls: --authority-evm takes the deployer EVM
address and records the Bech32 account paxd casts it to, the account the precompile resolves the
deployer to through the genesis address association init-chain.sh writes.

Guarantor identities are generated by the LayerX node after the Paxeer chain has started, so the
bring-up registers them through registerGuarantor and the authority activates them. --guarantor
is for a network whose guarantor set is known before the chain starts; a genesis bond is recorded
state, so the module account must hold it.
"""
import argparse
import json
import os
import re

ANCHOR_ADDRESS = '0000000000000000000000000000000000001014'
HASH = re.compile(r'^[0-9a-f]{64}$')
ADDRESS = re.compile(r'^[0-9a-f]{40}$')
BECH32 = 'qpzry9x8gf2tvdw0s3jn54khce6mua7l'
PREFIX = 'pax'
OPEN_ENDED_BATCH = 1 << 40


def require(condition, message):
    if not condition:
        raise SystemExit('anchor-genesis: ' + message)


def hash32(value, name):
    value = value.removeprefix('0x').lower()
    require(HASH.match(value) and value != '0' * 64, name + ' must be a nonzero 32-byte hex value')
    return value


def address20(value, name):
    value = value.removeprefix('0x').lower()
    require(ADDRESS.match(value) and value != '0' * 40, name + ' must be a nonzero 20-byte hex value')
    return value


def polymod(values):
    checksum = 1
    for value in values:
        top = checksum >> 25
        checksum = (checksum & 0x1ffffff) << 5 ^ value
        for index, generator in enumerate((0x3b6a57b2, 0x26508e6d, 0x1ea119fa, 0x3d4233dd, 0x2a1462b3)):
            checksum ^= generator if (top >> index) & 1 else 0
    return checksum


def expand(prefix):
    return [ord(c) >> 5 for c in prefix] + [0] + [ord(c) & 31 for c in prefix]


def bech32(prefix, payload):
    accumulator, bits, words = 0, 0, []
    for byte in payload:
        accumulator = (accumulator << 8) | byte
        bits += 8
        while bits >= 5:
            bits -= 5
            words.append((accumulator >> bits) & 31)
    if bits:
        words.append((accumulator << (5 - bits)) & 31)
    checksum = polymod(expand(prefix) + words + [0] * 6) ^ 1
    words += [(checksum >> 5 * (5 - index)) & 31 for index in range(6)]
    return prefix + '1' + ''.join(BECH32[word] for word in words)


def account(value, name):
    require(value.startswith(PREFIX + '1') and value == value.lower() and len(value) == len(PREFIX) + 1 + 32 + 6, name + ' must be a pax1 account of 20 bytes')
    words = [BECH32.find(c) for c in value[len(PREFIX) + 1:]]
    require(min(words) >= 0 and polymod(expand(PREFIX) + words) == 1, name + ' has a bad Bech32 checksum')
    return value


def guarantor(value):
    parts = value.split(':')
    require(len(parts) == 4 and parts[3].isdecimal() and int(parts[3]) > 0, 'guarantor is ID:SIGNER:OPERATOR:BOND')
    operator = parts[2] if parts[2].startswith(PREFIX + '1') else bech32(PREFIX, bytes.fromhex(address20(parts[2], 'guarantor operator')))
    return dict(id=hash32(parts[0], 'guarantor id'), signer=address20(parts[1], 'guarantor signer'),
                operator=account(operator, 'guarantor operator'), bond=str(int(parts[3])), status=2, registered_height=0)


def anchor(value):
    parts = value.split(':')
    require(len(parts) == 3 and parts[0].isdecimal() and parts[1].isdecimal(), 'anchor is BATCH:LAST_SEQUENCE:STATE_ROOT')
    return dict(set=True, batch_number=int(parts[0]), last_sequence=int(parts[1]), state_root=hash32(parts[2], 'anchor state root'))


def main():
    parser = argparse.ArgumentParser()
    authority = parser.add_mutually_exclusive_group(required=True)
    authority.add_argument('--authority')
    authority.add_argument('--authority-evm')
    parser.add_argument('--paxeer-chain-id', type=int, required=True)
    parser.add_argument('--network-id', type=int, required=True)
    parser.add_argument('--threshold', type=int, required=True)
    parser.add_argument('--min-bond', type=int, default=1_000_000)
    parser.add_argument('--bond-denom', default='uhpx')
    parser.add_argument('--challenge-bond', type=int, default=1_000_000)
    parser.add_argument('--challenge-window-seconds', type=int, default=0)
    parser.add_argument('--unbonding-delay-seconds', type=int, default=21 * 24 * 60 * 60)
    parser.add_argument('--max-attestation-delay-ms', type=int, default=3_600_000)
    parser.add_argument('--sequencer-id', required=True)
    parser.add_argument('--sequencer-public-key', required=True)
    parser.add_argument('--first-batch', type=int, default=1)
    parser.add_argument('--last-batch', type=int, default=OPEN_ENDED_BATCH)
    parser.add_argument('--guarantor', action='append', default=[], type=guarantor)
    parser.add_argument('--anchor', type=anchor, default=dict(set=False, batch_number=0, last_sequence=0, state_root='0' * 64))
    parser.add_argument('--permissionless-registration', action='store_true')
    parser.add_argument('--output', required=True)
    args = parser.parse_args()
    require(0 < args.paxeer_chain_id < 2 ** 64, 'the EVM chain id guarantors sign must be set')
    require(0 < args.network_id < 2 ** 32, 'network id')
    require(1 <= args.threshold <= 32, 'threshold must be within 1..32')
    require(args.min_bond > 0 and args.challenge_bond >= 0, 'bonds')
    require(0 < args.max_attestation_delay_ms < 2 ** 64, 'attestation delay')
    require(0 <= args.challenge_window_seconds < 2 ** 32 and 0 <= args.unbonding_delay_seconds < 2 ** 32, 'delays')
    require(0 < args.first_batch <= args.last_batch < 2 ** 64, 'sequencer batch range')
    require(re.match(r'^[a-zA-Z][a-zA-Z0-9/:._-]{2,127}$', args.bond_denom), 'bond denom')
    require(len({entry['id'] for entry in args.guarantor}) == len(args.guarantor)
            and len({entry['signer'] for entry in args.guarantor}) == len(args.guarantor), 'duplicate guarantor')
    require(not args.guarantor or len(args.guarantor) >= args.threshold, 'guarantor set cannot meet the threshold')
    require(all(int(entry['bond']) >= args.min_bond for entry in args.guarantor), 'guarantor bond below the minimum bond')
    if args.authority_evm:
        owner = bech32(PREFIX, bytes.fromhex(address20(args.authority_evm, 'authority')))
    else:
        owner = args.authority
    genesis = dict(
        params=dict(authority=account(owner, 'authority'), bond_denom=args.bond_denom, threshold=args.threshold,
                    min_bond=str(args.min_bond), unbonding_delay_seconds=args.unbonding_delay_seconds,
                    challenge_window_seconds=args.challenge_window_seconds, challenge_bond=str(args.challenge_bond),
                    max_attestation_delay_ms=args.max_attestation_delay_ms, paxeer_chain_id=args.paxeer_chain_id,
                    settlement_contract=ANCHOR_ADDRESS, network_id=args.network_id,
                    slash_fraction_equivocation='1.000000000000000000', slash_fraction_fraud='1.000000000000000000',
                    slash_fraction_availability='0.500000000000000000', reporter_share='0.100000000000000000',
                    slash_destination='', permissionless_registration=args.permissionless_registration),
        anchor=args.anchor,
        sequencers=[dict(sequencer_id=hash32(args.sequencer_id, 'sequencer id'),
                         public_key=hash32(args.sequencer_public_key, 'sequencer public key'),
                         first_batch_number=args.first_batch, last_batch_number=args.last_batch)],
        guarantors=sorted(args.guarantor, key=lambda entry: entry['id']), unbondings=[], checkpoints=[],
        has_latest_finalized=False, latest_finalized=0, availability=[], challenges=[], slash_records=[],
        next_challenge_id=1, next_unbonding_id=1)
    descriptor = os.open(args.output, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o644)
    with os.fdopen(descriptor, 'w') as output:
        json.dump(genesis, output, sort_keys=True, separators=(',', ':'))
        output.write('\n')


if __name__ == '__main__':
    main()
