version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: gomod
    directory: /hpx/registry
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: gomod
    directory: /sdk/cosmovisor
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: gomod
    directory: /sdk/ics23
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: npm
    directory: /contracts
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /integration_test/dapp_tests
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: npm
    directory: /integration_test/rpc_tests
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: cargo
    directory: /wasm-runtime/libwasmvm
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
