// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: layerxcustody/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the layerxcustody module's genesis state.
type GenesisState struct {
	Params           Params            `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Assets           []AssetMapping    `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets"`
	DepositCount     uint64            `protobuf:"varint,3,opt,name=deposit_count,json=depositCount,proto3" json:"deposit_count,omitempty"`
	Deposits         []Deposit         `protobuf:"bytes,4,rep,name=deposits,proto3" json:"deposits"`
	DepositNonces    []DepositNonce    `protobuf:"bytes,5,rep,name=deposit_nonces,json=depositNonces,proto3" json:"deposit_nonces"`
	Claims           []Claim           `protobuf:"bytes,6,rep,name=claims,proto3" json:"claims"`
	Nullifiers       []Nullifier       `protobuf:"bytes,7,rep,name=nullifiers,proto3" json:"nullifiers"`
	Checkpoints      []Checkpoint      `protobuf:"bytes,8,rep,name=checkpoints,proto3" json:"checkpoints"`
	ConsumedBalances []ConsumedBalance `protobuf:"bytes,9,rep,name=consumed_balances,json=consumedBalances,proto3" json:"consumed_balances"`
	Totals           []AssetTotals     `protobuf:"bytes,10,rep,name=totals,proto3" json:"totals"`
	Emergency        bool              `protobuf:"varint,11,opt,name=emergency,proto3" json:"emergency,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcfbe6a787fa399c, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetAssets() []AssetMapping {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *GenesisState) GetDepositCount() uint64 {
	if m != nil {
		return m.DepositCount
	}
	return 0
}

func (m *GenesisState) GetDeposits() []Deposit {
	if m != nil {
		return m.Deposits
	}
	return nil
}

func (m *GenesisState) GetDepositNonces() []DepositNonce {
	if m != nil {
		return m.DepositNonces
	}
	return nil
}

func (m *GenesisState) GetClaims() []Claim {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *GenesisState) GetNullifiers() []Nullifier {
	if m != nil {
		return m.Nullifiers
	}
	return nil
}

func (m *GenesisState) GetCheckpoints() []Checkpoint {
	if m != nil {
		return m.Checkpoints
	}
	return nil
}

func (m *GenesisState) GetConsumedBalances() []ConsumedBalance {
	if m != nil {
		return m.ConsumedBalances
	}
	return nil
}

func (m *GenesisState) GetTotals() []AssetTotals {
	if m != nil {
		return m.Totals
	}
	return nil
}

func (m *GenesisState) GetEmergency() bool {
	if m != nil {
		return m.Emergency
	}
	return false
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "paxprotocol.paxchain.layerxcustody.GenesisState")
}

func init() { proto.RegisterFile("layerxcustody/genesis.proto", fileDescriptor_bcfbe6a787fa399c) }

var fileDescriptor_bcfbe6a787fa399c = []byte{
	// 481 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0x6e, 0xd3, 0x30,
	0x18, 0xc7, 0x1b, 0x56, 0x42, 0xe7, 0x0e, 0x04, 0x16, 0x07, 0x53, 0x50, 0xa8, 0xc6, 0xa5, 0x80,
	0x9a, 0xa0, 0xed, 0x09, 0xe8, 0x90, 0xc6, 0xa5, 0x15, 0xea, 0x10, 0x07, 0x04, 0x9a, 0x5c, 0xd7,
	0x4b, 0xad, 0x25, 0xb6, 0x95, 0xcf, 0x11, 0xed, 0x5b, 0xf0, 0x54, 0x68, 0xc7, 0x1d, 0x39, 0x21,
	0xd4, 0xbe, 0x08, 0x8a, 0xed, 0x8c, 0xe5, 0xb4, 0xdc, 0x9c, 0xbf, 0xf3, 0xfb, 0xfd, 0x3f, 0x5b,
	0x09, 0x7a, 0x9e, 0xd1, 0x0d, 0x2f, 0xd6, 0xac, 0x04, 0xa3, 0x96, 0x9b, 0x24, 0xe5, 0x92, 0x83,
	0x80, 0x58, 0x17, 0xca, 0x28, 0x7c, 0xa8, 0xe9, 0xda, 0xae, 0x98, 0xca, 0x62, 0x4d, 0xd7, 0x6c,
	0x45, 0x85, 0x8c, 0x1b, 0xc4, 0xe0, 0x69, 0xaa, 0x52, 0x65, 0x5f, 0x4a, 0xaa, 0x95, 0x23, 0x07,
	0x83, 0xa6, 0x56, 0xd3, 0x82, 0xe6, 0xde, 0x3a, 0x78, 0xd6, 0xdc, 0x03, 0x43, 0x0d, 0x77, 0x5b,
	0x87, 0xbf, 0x42, 0x74, 0x70, 0xea, 0x46, 0x38, 0xab, 0x62, 0xfc, 0x11, 0x85, 0x8e, 0x25, 0xc1,
	0x30, 0x18, 0xf5, 0x8f, 0xde, 0xc4, 0x77, 0x8f, 0x14, 0x7f, 0xb2, 0xc4, 0xa4, 0x7b, 0xf5, 0xe7,
	0x65, 0x67, 0xee, 0x79, 0x3c, 0x43, 0x21, 0x05, 0xe0, 0x06, 0xc8, 0xbd, 0xe1, 0xde, 0xa8, 0x7f,
	0xf4, 0xae, 0x8d, 0xe9, 0x7d, 0x45, 0x4c, 0xa9, 0xd6, 0x42, 0xa6, 0xb5, 0xcf, 0x59, 0xf0, 0x2b,
	0xf4, 0x70, 0xc9, 0xb5, 0x02, 0x61, 0xce, 0x99, 0x2a, 0xa5, 0x21, 0x7b, 0xc3, 0x60, 0xd4, 0x9d,
	0x1f, 0xf8, 0xf0, 0xa4, 0xca, 0xf0, 0x14, 0xf5, 0xfc, 0x33, 0x90, 0xae, 0xad, 0x7d, 0xdb, 0xa6,
	0xf6, 0x83, 0x63, 0x7c, 0xe3, 0x8d, 0x02, 0x7f, 0x47, 0x8f, 0xea, 0x4e, 0xa9, 0x24, 0xe3, 0x40,
	0xee, 0xb7, 0x3f, 0x8b, 0x97, 0xce, 0x2a, 0xd0, 0x9b, 0xeb, 0x13, 0xd8, 0x0c, 0xf0, 0x29, 0x0a,
	0x59, 0x46, 0x45, 0x0e, 0x24, 0xb4, 0xda, 0xd7, 0x6d, 0xb4, 0x27, 0x15, 0x51, 0xdf, 0x8d, 0xc3,
	0xf1, 0x19, 0x42, 0xb2, 0xcc, 0x32, 0x71, 0x21, 0x78, 0x01, 0xe4, 0x81, 0x95, 0x8d, 0xdb, 0xc8,
	0x66, 0x35, 0xe5, 0x85, 0xb7, 0x34, 0xf8, 0x0b, 0xea, 0xb3, 0x15, 0x67, 0x97, 0x5a, 0x09, 0x69,
	0x80, 0xf4, 0xac, 0x35, 0x6e, 0x35, 0xe2, 0x0d, 0xe6, 0xb5, 0xb7, 0x45, 0xf8, 0x02, 0x3d, 0x61,
	0x4a, 0x42, 0x99, 0xf3, 0xe5, 0xf9, 0x82, 0x66, 0xd4, 0xde, 0xeb, 0xbe, 0xb5, 0x1f, 0xb7, 0xb2,
	0x7b, 0x78, 0xe2, 0x58, 0x5f, 0xf1, 0x98, 0x35, 0x63, 0xc0, 0x53, 0x14, 0x1a, 0x65, 0x68, 0x06,
	0x04, 0x59, 0x79, 0xd2, 0xfa, 0x03, 0xfc, 0x6c, 0xb1, 0xfa, 0x8e, 0x9d, 0x04, 0xbf, 0x40, 0xfb,
	0x3c, 0xe7, 0x45, 0xca, 0x25, 0xdb, 0x90, 0xfe, 0x30, 0x18, 0xf5, 0xe6, 0xff, 0x83, 0xc9, 0xb7,
	0xab, 0x6d, 0x14, 0x5c, 0x6f, 0xa3, 0xe0, 0xef, 0x36, 0x0a, 0x7e, 0xee, 0xa2, 0xce, 0xf5, 0x2e,
	0xea, 0xfc, 0xde, 0x45, 0x9d, 0xaf, 0x93, 0x54, 0x98, 0x55, 0xb9, 0x88, 0x99, 0xca, 0x13, 0x10,
	0x4b, 0xa1, 0x0a, 0x3a, 0xce, 0xe8, 0x02, 0x12, 0x4d, 0xd7, 0x9c, 0x17, 0x63, 0xc9, 0xcd, 0x0f,
	0x55, 0x5c, 0x26, 0xb9, 0x5a, 0x96, 0x19, 0x87, 0xa4, 0xf9, 0xb3, 0x9a, 0x8d, 0xe6, 0xb0, 0x08,
	0xed, 0xd8, 0xc7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x71, 0xf4, 0xa3, 0xd2, 0x3d, 0x04, 0x00,
	0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Emergency {
		i--
		if m.Emergency {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if len(m.Totals) > 0 {
		for iNdEx := len(m.Totals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Totals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.ConsumedBalances) > 0 {
		for iNdEx := len(m.ConsumedBalances) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ConsumedBalances[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.Checkpoints) > 0 {
		for iNdEx := len(m.Checkpoints) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Checkpoints[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.Nullifiers) > 0 {
		for iNdEx := len(m.Nullifiers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Nullifiers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Claims) > 0 {
		for iNdEx := len(m.Claims) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Claims[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.DepositNonces) > 0 {
		for iNdEx := len(m.DepositNonces) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DepositNonces[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Deposits) > 0 {
		for iNdEx := len(m.Deposits) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Deposits[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.DepositCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.DepositCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Assets) > 0 {
		for iNdEx := len(m.Assets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Assets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Assets) > 0 {
		for _, e := range m.Assets {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.DepositCount != 0 {
		n += 1 + sovGenesis(uint64(m.DepositCount))
	}
	if len(m.Deposits) > 0 {
		for _, e := range m.Deposits {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.DepositNonces) > 0 {
		for _, e := range m.DepositNonces {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Claims) > 0 {
		for _, e := range m.Claims {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Nullifiers) > 0 {
		for _, e := range m.Nullifiers {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Checkpoints) > 0 {
		for _, e := range m.Checkpoints {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ConsumedBalances) > 0 {
		for _, e := range m.ConsumedBalances {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Totals) > 0 {
		for _, e := range m.Totals {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.Emergency {
		n += 2
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Assets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Assets = append(m.Assets, AssetMapping{})
			if err := m.Assets[len(m.Assets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositCount", wireType)
			}
			m.DepositCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepositCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deposits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Deposits = append(m.Deposits, Deposit{})
			if err := m.Deposits[len(m.Deposits)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositNonces", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositNonces = append(m.DepositNonces, DepositNonce{})
			if err := m.DepositNonces[len(m.DepositNonces)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claims", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Claims = append(m.Claims, Claim{})
			if err := m.Claims[len(m.Claims)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nullifiers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nullifiers = append(m.Nullifiers, Nullifier{})
			if err := m.Nullifiers[len(m.Nullifiers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Checkpoints", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Checkpoints = append(m.Checkpoints, Checkpoint{})
			if err := m.Checkpoints[len(m.Checkpoints)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumedBalances", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsumedBalances = append(m.ConsumedBalances, ConsumedBalance{})
			if err := m.ConsumedBalances[len(m.ConsumedBalances)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Totals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Totals = append(m.Totals, AssetTotals{})
			if err := m.Totals[len(m.Totals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Emergency", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Emergency = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
