// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: layerxcustody/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SequencerAuthorization is the LayerX sequencer authority valid for an
// inclusive batch range. Identifiers are 64 lowercase hex characters.
type SequencerAuthorization struct {
	SequencerId      string `protobuf:"bytes,1,opt,name=sequencer_id,json=sequencerId,proto3" json:"sequencer_id,omitempty"`
	PublicKey        string `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	FirstBatchNumber uint64 `protobuf:"varint,3,opt,name=first_batch_number,json=firstBatchNumber,proto3" json:"first_batch_number,omitempty"`
	LastBatchNumber  uint64 `protobuf:"varint,4,opt,name=last_batch_number,json=lastBatchNumber,proto3" json:"last_batch_number,omitempty"`
}

func (m *SequencerAuthorization) Reset()         { *m = SequencerAuthorization{} }
func (m *SequencerAuthorization) String() string { return proto.CompactTextString(m) }
func (*SequencerAuthorization) ProtoMessage()    {}
func (*SequencerAuthorization) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ac446e977eda08c, []int{0}
}
func (m *SequencerAuthorization) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SequencerAuthorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SequencerAuthorization.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SequencerAuthorization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SequencerAuthorization.Merge(m, src)
}
func (m *SequencerAuthorization) XXX_Size() int {
	return m.Size()
}
func (m *SequencerAuthorization) XXX_DiscardUnknown() {
	xxx_messageInfo_SequencerAuthorization.DiscardUnknown(m)
}

var xxx_messageInfo_SequencerAuthorization proto.InternalMessageInfo

func (m *SequencerAuthorization) GetSequencerId() string {
	if m != nil {
		return m.SequencerId
	}
	return ""
}

func (m *SequencerAuthorization) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *SequencerAuthorization) GetFirstBatchNumber() uint64 {
	if m != nil {
		return m.FirstBatchNumber
	}
	return 0
}

func (m *SequencerAuthorization) GetLastBatchNumber() uint64 {
	if m != nil {
		return m.LastBatchNumber
	}
	return 0
}

// Params defines the parameters of the layerxcustody module.
type Params struct {
	// authority is the bech32 account allowed to change params, the asset map,
	// finalized checkpoints, the emergency flag and to cancel pending claims.
	// Empty selects the governance module account.
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// network_id is the LayerX network every batch header and withdrawal must name.
	NetworkId uint32 `protobuf:"varint,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// withdrawal_delay_seconds is the challenge window between queueing and
	// paying a withdrawal claim.
	WithdrawalDelaySeconds uint64 `protobuf:"varint,3,opt,name=withdrawal_delay_seconds,json=withdrawalDelaySeconds,proto3" json:"withdrawal_delay_seconds,omitempty"`
	// forced_exit_delay_seconds is the window between requesting and paying a
	// forced exit.
	ForcedExitDelaySeconds uint64 `protobuf:"varint,4,opt,name=forced_exit_delay_seconds,json=forcedExitDelaySeconds,proto3" json:"forced_exit_delay_seconds,omitempty"`
	// liveness_bound_seconds is the checkpoint silence after which forced exits
	// become eligible without an emergency declaration.
	LivenessBoundSeconds uint64 `protobuf:"varint,5,opt,name=liveness_bound_seconds,json=livenessBoundSeconds,proto3" json:"liveness_bound_seconds,omitempty"`
	// sequencer_authorizations backs AnchorReader until the anchor module lands.
	SequencerAuthorizations []SequencerAuthorization `protobuf:"bytes,6,rep,name=sequencer_authorizations,json=sequencerAuthorizations,proto3" json:"sequencer_authorizations"`
	// deposit_root_authority is the Ed25519 public key, 64 lowercase hex
	// characters, that signs deposit root registrations. Empty refuses them all.
	DepositRootAuthority string `protobuf:"bytes,7,opt,name=deposit_root_authority,json=depositRootAuthority,proto3" json:"deposit_root_authority,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ac446e977eda08c, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *Params) GetNetworkId() uint32 {
	if m != nil {
		return m.NetworkId
	}
	return 0
}

func (m *Params) GetWithdrawalDelaySeconds() uint64 {
	if m != nil {
		return m.WithdrawalDelaySeconds
	}
	return 0
}

func (m *Params) GetForcedExitDelaySeconds() uint64 {
	if m != nil {
		return m.ForcedExitDelaySeconds
	}
	return 0
}

func (m *Params) GetLivenessBoundSeconds() uint64 {
	if m != nil {
		return m.LivenessBoundSeconds
	}
	return 0
}

func (m *Params) GetSequencerAuthorizations() []SequencerAuthorization {
	if m != nil {
		return m.SequencerAuthorizations
	}
	return nil
}

func (m *Params) GetDepositRootAuthority() string {
	if m != nil {
		return m.DepositRootAuthority
	}
	return ""
}

func init() {
	proto.RegisterType((*SequencerAuthorization)(nil), "paxprotocol.paxchain.layerxcustody.SequencerAuthorization")
	proto.RegisterType((*Params)(nil), "paxprotocol.paxchain.layerxcustody.Params")
}

func init() { proto.RegisterFile("layerxcustody/params.proto", fileDescriptor_1ac446e977eda08c) }

var fileDescriptor_1ac446e977eda08c = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xc1, 0x6e, 0xd3, 0x4c,
	0x14, 0x85, 0xe3, 0x3f, 0xf9, 0x83, 0x32, 0x05, 0x01, 0x56, 0x14, 0x4c, 0x05, 0x6e, 0xc8, 0x2a,
	0x42, 0xd4, 0x96, 0x80, 0x05, 0x74, 0x57, 0x0b, 0x16, 0x15, 0x12, 0x42, 0xee, 0x0e, 0x21, 0x8d,
	0xc6, 0x9e, 0xdb, 0x78, 0x54, 0xc7, 0xd7, 0xcc, 0x8c, 0x89, 0x0d, 0x2f, 0xc1, 0x23, 0x20, 0xf1,
	0x16, 0x3c, 0x41, 0x97, 0x5d, 0xb2, 0x42, 0x28, 0xd9, 0xf0, 0x18, 0xc8, 0x63, 0xa7, 0x69, 0xaa,
	0x4a, 0xec, 0x46, 0xe7, 0x3b, 0x47, 0x3a, 0xf7, 0x5e, 0x9b, 0xec, 0xa6, 0xac, 0x02, 0x59, 0xc6,
	0x85, 0xd2, 0xc8, 0x2b, 0x3f, 0x67, 0x92, 0xcd, 0x95, 0x97, 0x4b, 0xd4, 0x68, 0x4f, 0x72, 0x56,
	0x9a, 0x57, 0x8c, 0xa9, 0x97, 0xb3, 0x32, 0x4e, 0x98, 0xc8, 0xbc, 0xad, 0xc0, 0xee, 0x70, 0x86,
	0x33, 0x34, 0x26, 0xbf, 0x7e, 0x35, 0xc9, 0xc9, 0x0f, 0x8b, 0x8c, 0x8e, 0xe1, 0x63, 0x01, 0x59,
	0x0c, 0xf2, 0xb0, 0xd0, 0x09, 0x4a, 0xf1, 0x99, 0x69, 0x81, 0x99, 0xfd, 0x88, 0xdc, 0x54, 0x6b,
	0x42, 0x05, 0x77, 0xac, 0xb1, 0x35, 0x1d, 0x84, 0x3b, 0x17, 0xda, 0x11, 0xb7, 0x1f, 0x12, 0x92,
	0x17, 0x51, 0x2a, 0x62, 0x7a, 0x0a, 0x95, 0xf3, 0x9f, 0x31, 0x0c, 0x1a, 0xe5, 0x0d, 0x54, 0xf6,
	0x13, 0x62, 0x9f, 0x08, 0xa9, 0x34, 0x8d, 0x98, 0x8e, 0x13, 0x9a, 0x15, 0xf3, 0x08, 0xa4, 0xd3,
	0x1d, 0x5b, 0xd3, 0x5e, 0x78, 0xc7, 0x90, 0xa0, 0x06, 0x6f, 0x8d, 0x6e, 0x3f, 0x26, 0x77, 0x53,
	0x76, 0xd5, 0xdc, 0x33, 0xe6, 0xdb, 0x35, 0xb8, 0xe4, 0x3d, 0xe8, 0xfd, 0xf9, 0xb6, 0x67, 0x4d,
	0xbe, 0x77, 0x49, 0xff, 0x9d, 0xd9, 0x83, 0xfd, 0x80, 0x0c, 0x58, 0xd3, 0x5e, 0x57, 0x6d, 0xd3,
	0x8d, 0x50, 0xf7, 0xcc, 0x40, 0x2f, 0x50, 0x9e, 0xd6, 0x83, 0xd4, 0x3d, 0x6f, 0x85, 0x83, 0x56,
	0x39, 0xe2, 0xf6, 0x0b, 0xe2, 0x2c, 0x84, 0x4e, 0xb8, 0x64, 0x0b, 0x96, 0x52, 0x0e, 0x29, 0xab,
	0xa8, 0x82, 0x18, 0x33, 0xae, 0xda, 0xb6, 0xa3, 0x0d, 0x7f, 0x55, 0xe3, 0xe3, 0x86, 0xda, 0x2f,
	0xc9, 0xfd, 0x13, 0x94, 0x31, 0x70, 0x0a, 0xa5, 0xd0, 0x57, 0xa2, 0x4d, 0xf7, 0x51, 0x63, 0x78,
	0x5d, 0x0a, 0xbd, 0x15, 0x7d, 0x4e, 0x46, 0xa9, 0xf8, 0x04, 0x19, 0x28, 0x45, 0x23, 0x2c, 0x32,
	0x7e, 0x91, 0xfb, 0xdf, 0xe4, 0x86, 0x6b, 0x1a, 0xd4, 0x70, 0x9d, 0xfa, 0x42, 0x9c, 0xcd, 0x51,
	0xd8, 0xe5, 0x7b, 0x29, 0xa7, 0x3f, 0xee, 0x4e, 0x77, 0x9e, 0x1e, 0x78, 0xff, 0xfe, 0x18, 0xbc,
	0xeb, 0x4f, 0x1e, 0xf4, 0xce, 0x7e, 0xed, 0x75, 0xc2, 0x7b, 0xea, 0x5a, 0x6a, 0x2a, 0x73, 0xc8,
	0x51, 0x09, 0x4d, 0x25, 0xa2, 0xa6, 0x9b, 0x8d, 0xdf, 0x30, 0x1b, 0x1f, 0xb6, 0x34, 0x44, 0xd4,
	0x87, 0x6b, 0x16, 0x7c, 0x38, 0x5b, 0xba, 0xd6, 0xf9, 0xd2, 0xb5, 0x7e, 0x2f, 0x5d, 0xeb, 0xeb,
	0xca, 0xed, 0x9c, 0xaf, 0xdc, 0xce, 0xcf, 0x95, 0xdb, 0x79, 0x1f, 0xcc, 0x84, 0x4e, 0x8a, 0xc8,
	0x8b, 0x71, 0xee, 0x2b, 0xc1, 0x05, 0x4a, 0xb6, 0x9f, 0xb2, 0x48, 0xf9, 0x39, 0x2b, 0x01, 0xe4,
	0x7e, 0x7b, 0x21, 0x7f, 0x8e, 0xbc, 0x48, 0x41, 0xf9, 0xdb, 0x7f, 0x80, 0xae, 0x72, 0x50, 0x51,
	0xdf, 0x8c, 0xfa, 0xec, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x7f, 0xeb, 0xcf, 0x1f, 0x03,
	0x00, 0x00,
}

func (this *SequencerAuthorization) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SequencerAuthorization)
	if !ok {
		that2, ok := that.(SequencerAuthorization)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.SequencerId != that1.SequencerId {
		return false
	}
	if this.PublicKey != that1.PublicKey {
		return false
	}
	if this.FirstBatchNumber != that1.FirstBatchNumber {
		return false
	}
	if this.LastBatchNumber != that1.LastBatchNumber {
		return false
	}
	return true
}
func (m *SequencerAuthorization) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SequencerAuthorization) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SequencerAuthorization) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastBatchNumber != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.LastBatchNumber))
		i--
		dAtA[i] = 0x20
	}
	if m.FirstBatchNumber != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.FirstBatchNumber))
		i--
		dAtA[i] = 0x18
	}
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintParams(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SequencerId) > 0 {
		i -= len(m.SequencerId)
		copy(dAtA[i:], m.SequencerId)
		i = encodeVarintParams(dAtA, i, uint64(len(m.SequencerId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DepositRootAuthority) > 0 {
		i -= len(m.DepositRootAuthority)
		copy(dAtA[i:], m.DepositRootAuthority)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DepositRootAuthority)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.SequencerAuthorizations) > 0 {
		for iNdEx := len(m.SequencerAuthorizations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SequencerAuthorizations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.LivenessBoundSeconds != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.LivenessBoundSeconds))
		i--
		dAtA[i] = 0x28
	}
	if m.ForcedExitDelaySeconds != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ForcedExitDelaySeconds))
		i--
		dAtA[i] = 0x20
	}
	if m.WithdrawalDelaySeconds != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.WithdrawalDelaySeconds))
		i--
		dAtA[i] = 0x18
	}
	if m.NetworkId != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.NetworkId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SequencerAuthorization) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SequencerId)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.FirstBatchNumber != 0 {
		n += 1 + sovParams(uint64(m.FirstBatchNumber))
	}
	if m.LastBatchNumber != 0 {
		n += 1 + sovParams(uint64(m.LastBatchNumber))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.NetworkId != 0 {
		n += 1 + sovParams(uint64(m.NetworkId))
	}
	if m.WithdrawalDelaySeconds != 0 {
		n += 1 + sovParams(uint64(m.WithdrawalDelaySeconds))
	}
	if m.ForcedExitDelaySeconds != 0 {
		n += 1 + sovParams(uint64(m.ForcedExitDelaySeconds))
	}
	if m.LivenessBoundSeconds != 0 {
		n += 1 + sovParams(uint64(m.LivenessBoundSeconds))
	}
	if len(m.SequencerAuthorizations) > 0 {
		for _, e := range m.SequencerAuthorizations {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	l = len(m.DepositRootAuthority)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SequencerAuthorization) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SequencerAuthorization: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SequencerAuthorization: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SequencerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SequencerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstBatchNumber", wireType)
			}
			m.FirstBatchNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FirstBatchNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastBatchNumber", wireType)
			}
			m.LastBatchNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastBatchNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkId", wireType)
			}
			m.NetworkId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NetworkId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalDelaySeconds", wireType)
			}
			m.WithdrawalDelaySeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WithdrawalDelaySeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForcedExitDelaySeconds", wireType)
			}
			m.ForcedExitDelaySeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ForcedExitDelaySeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LivenessBoundSeconds", wireType)
			}
			m.LivenessBoundSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LivenessBoundSeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SequencerAuthorizations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SequencerAuthorizations = append(m.SequencerAuthorizations, SequencerAuthorization{})
			if err := m.SequencerAuthorizations[len(m.SequencerAuthorizations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositRootAuthority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositRootAuthority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
