// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: layerxcustody/state.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ClaimKind separates proof-carrying withdrawals from forced exits.
type ClaimKind int32

const (
	ClaimKind_CLAIM_KIND_UNSPECIFIED ClaimKind = 0
	ClaimKind_CLAIM_KIND_WITHDRAWAL  ClaimKind = 1
	ClaimKind_CLAIM_KIND_FORCED_EXIT ClaimKind = 2
)

var ClaimKind_name = map[int32]string{
	0: "CLAIM_KIND_UNSPECIFIED",
	1: "CLAIM_KIND_WITHDRAWAL",
	2: "CLAIM_KIND_FORCED_EXIT",
}

var ClaimKind_value = map[string]int32{
	"CLAIM_KIND_UNSPECIFIED": 0,
	"CLAIM_KIND_WITHDRAWAL":  1,
	"CLAIM_KIND_FORCED_EXIT": 2,
}

func (x ClaimKind) String() string {
	return proto.EnumName(ClaimKind_name, int32(x))
}

func (ClaimKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e53959e114ebead8, []int{0}
}

// ClaimStatus mirrors WithdrawalClaims.ClaimStatus.
type ClaimStatus int32

const (
	ClaimStatus_CLAIM_STATUS_NONE      ClaimStatus = 0
	ClaimStatus_CLAIM_STATUS_PENDING   ClaimStatus = 1
	ClaimStatus_CLAIM_STATUS_PAID      ClaimStatus = 2
	ClaimStatus_CLAIM_STATUS_CANCELLED ClaimStatus = 3
)

var ClaimStatus_name = map[int32]string{
	0: "CLAIM_STATUS_NONE",
	1: "CLAIM_STATUS_PENDING",
	2: "CLAIM_STATUS_PAID",
	3: "CLAIM_STATUS_CANCELLED",
}

var ClaimStatus_value = map[string]int32{
	"CLAIM_STATUS_NONE":      0,
	"CLAIM_STATUS_PENDING":   1,
	"CLAIM_STATUS_PAID":      2,
	"CLAIM_STATUS_CANCELLED": 3,
}

func (x ClaimStatus) String() string {
	return proto.EnumName(ClaimStatus_name, int32(x))
}

func (ClaimStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e53959e114ebead8, []int{1}
}

// NullifierStatus mirrors WithdrawalNullifierRegistry.Status.
type NullifierStatus int32

const (
	NullifierStatus_NULLIFIER_STATUS_NONE      NullifierStatus = 0
	NullifierStatus_NULLIFIER_STATUS_RESERVED  NullifierStatus = 1
	NullifierStatus_NULLIFIER_STATUS_CONSUMED  NullifierStatus = 2
	NullifierStatus_NULLIFIER_STATUS_CANCELLED NullifierStatus = 3
)

var NullifierStatus_name = map[int32]string{
	0: "NULLIFIER_STATUS_NONE",
	1: "NULLIFIER_STATUS_RESERVED",
	2: "NULLIFIER_STATUS_CONSUMED",
	3: "NULLIFIER_STATUS_CANCELLED",
}

var NullifierStatus_value = map[string]int32{
	"NULLIFIER_STATUS_NONE":      0,
	"NULLIFIER_STATUS_RESERVED":  1,
	"NULLIFIER_STATUS_CONSUMED":  2,
	"NULLIFIER_STATUS_CANCELLED": 3,
}

func (x NullifierStatus) String() string {
	return proto.EnumName(NullifierStatus_name, int32(x))
}

func (NullifierStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e53959e114ebead8, []int{2}
}

// AssetMapping binds one LayerX 32-byte asset identifier to the Paxeer bank
// denom that custody holds for it.
type AssetMapping struct {
	// asset_id is 64 lowercase hex characters.
	AssetId string `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Denom   string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	// pointer is the 0x-prefixed ERC20 pointer contract of denom, or empty.
	Pointer string `protobuf:"bytes,3,opt,name=pointer,proto3" json:"pointer,omitempty"`
	Enabled bool   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Paused  bool   `protobuf:"varint,5,opt,name=paused,proto3" json:"paused,omitempty"`
	// minimum_deposit and custody_cap are decimal base-unit amounts; an empty
	// custody_cap means uncapped.
	MinimumDeposit string `protobuf:"bytes,6,opt,name=minimum_deposit,json=minimumDeposit,proto3" json:"minimum_deposit,omitempty"`
	CustodyCap     string `protobuf:"bytes,7,opt,name=custody_cap,json=custodyCap,proto3" json:"custody_cap,omitempty"`
}

func (m *AssetMapping) Reset()         { *m = AssetMapping{} }
func (m *AssetMapping) String() string { return proto.CompactTextString(m) }
func (*AssetMapping) ProtoMessage()    {}
func (*AssetMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_e53959e114ebead8, []int{0}
}
func (m *AssetMapping) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AssetMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AssetMapping.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AssetMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetMapping.Merge(m, src)
}
func (m *AssetMapping) XXX_Size() int {
	return m.Size()
}
func (m *AssetMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetMapping.DiscardUnknown(m)
}

var xxx_messageInfo_AssetMapping proto.InternalMessageInfo

func (m *AssetMapping) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *AssetMapping) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *AssetMapping) GetPointer() string {
	if m != nil {
		return m.Pointer
	}
	return ""
}

func (m *AssetMapping) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *AssetMapping) GetPaused() bool {
	if m != nil {
		return m.Paused
	}
	return false
}

func (m *AssetMapping) GetMinimumDeposit() string {
	if m != nil {
		return m.MinimumDeposit
	}
	return ""
}

func (m *AssetMapping) GetCustodyCap() string {
	if m != nil {
		return m.CustodyCap
	}
	return ""
}

// Deposit is one recorded custody deposit.
type Deposit struct {
	DepositId string `protobuf:"bytes,1,opt,name=deposit_id,json=depositId,proto3" json:"deposit_id,omitempty"`
	Index     uint64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// depositor is the 0x-prefixed EVM address that paid.
	Depositor string `protobuf:"bytes,3,opt,name=depositor,proto3" json:"depositor,omitempty"`
	// beneficiary is the 32-byte LayerX account identifier, exactly as the
	// Solidity vault carried it.
	Beneficiary string `protobuf:"bytes,4,opt,name=beneficiary,proto3" json:"beneficiary,omitempty"`
	AssetId     string `protobuf:"bytes,5,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Denom       string `protobuf:"bytes,6,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount      string `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Nonce       uint64 `protobuf:"varint,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Height      int64  `protobuf:"varint,9,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *Deposit) Reset()         { *m = Deposit{} }
func (m *Deposit) String() string { return proto.CompactTextString(m) }
func (*Deposit) ProtoMessage()    {}
func (*Deposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_e53959e114ebead8, []int{1}
}
func (m *Deposit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Deposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Deposit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Deposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deposit.Merge(m, src)
}
func (m *Deposit) XXX_Size() int {
	return m.Size()
}
func (m *Deposit) XXX_DiscardUnknown() {
	xxx_messageInfo_Deposit.DiscardUnknown(m)
}

var xxx_messageInfo_Deposit proto.InternalMessageInfo

func (m *Deposit) GetDepositId() string {
	if m != nil {
		return m.DepositId
	}
	return ""
}

func (m *Deposit) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Deposit) GetDepositor() string {
	if m != nil {
		return m.Depositor
	}
	return ""
}

func (m *Deposit) GetBeneficiary() string {
	if m != nil {
		return m.Beneficiary
	}
	return ""
}

func (m *Deposit) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *Deposit) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *Deposit) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Deposit) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Deposit) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

// DepositNonce is the per depositor and asset deposit nonce.
type DepositNonce struct {
	Depositor string `protobuf:"bytes,1,opt,name=depositor,proto3" json:"depositor,omitempty"`
	AssetId   string `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Nonce     uint64 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (m *DepositNonce) Reset()         { *m = DepositNonce{} }
func (m *DepositNonce) String() string { return proto.CompactTextString(m) }
func (*DepositNonce) ProtoMessage()    {}
func (*DepositNonce) Descriptor() ([]byte, []int) {
	return fileDescriptor_e53959e114ebead8, []int{2}
}
func (m *DepositNonce) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DepositNonce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DepositNonce.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DepositNonce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositNonce.Merge(m, src)
}
func (m *DepositNonce) XXX_Size() int {
	return m.Size()
}
func (m *DepositNonce) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositNonce.DiscardUnknown(m)
}

var xxx_messageInfo_DepositNonce proto.InternalMessageInfo

func (m *DepositNonce) GetDepositor() string {
	if m != nil {
		return m.Depositor
	}
	return ""
}

func (m *DepositNonce) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *DepositNonce) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

// Claim is one queued payout: a withdrawal claim or a forced-exit request.
type Claim struct {
	ClaimId      string      `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	Kind         ClaimKind   `protobuf:"varint,2,opt,name=kind,proto3,enum=paxprotocol.paxchain.layerxcustody.ClaimKind" json:"kind,omitempty"`
	Status       ClaimStatus `protobuf:"varint,3,opt,name=status,proto3,enum=paxprotocol.paxchain.layerxcustody.ClaimStatus" json:"status,omitempty"`
	Nullifier    string      `protobuf:"bytes,4,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
	WithdrawalId string      `protobuf:"bytes,5,opt,name=withdrawal_id,json=withdrawalId,proto3" json:"withdrawal_id,omitempty"`
	Account      string      `protobuf:"bytes,6,opt,name=account,proto3" json:"account,omitempty"`
	AssetId      string      `protobuf:"bytes,7,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Denom        string      `protobuf:"bytes,8,opt,name=denom,proto3" json:"denom,omitempty"`
	// recipient is the 0x-prefixed EVM address that is paid.
	Recipient   string `protobuf:"bytes,9,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Amount      string `protobuf:"bytes,10,opt,name=amount,proto3" json:"amount,omitempty"`
	BatchNumber uint64 `protobuf:"varint,11,opt,name=batch_number,json=batchNumber,proto3" json:"batch_number,omitempty"`
	// anchor is the withdrawal request anchor or the forced-exit state root.
	Anchor string `protobuf:"bytes,12,opt,name=anchor,proto3" json:"anchor,omitempty"`
	// available_at is the unix second from which the claim can be paid.
	AvailableAt int64 `protobuf:"varint,13,opt,name=available_at,json=availableAt,proto3" json:"available_at,omitempty"`
}

func (m *Claim) Reset()         { *m = Claim{} }
func (m *Claim) String() string { return proto.CompactTextString(m) }
func (*Claim) ProtoMessage()    {}
func (*Claim) Descriptor() ([]byte, []int) {
	return fileDescriptor_e53959e114ebead8, []int{3}
}
func (m *Claim) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Claim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Claim.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Claim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Claim.Merge(m, src)
}
func (m *Claim) XXX_Size() int {
	return m.Size()
}
func (m *Claim) XXX_DiscardUnknown() {
	xxx_messageInfo_Claim.DiscardUnknown(m)
}

var xxx_messageInfo_Claim proto.InternalMessageInfo

func (m *Claim) GetClaimId() string {
	if m != nil {
		return m.ClaimId
	}
	return ""
}

func (m *Claim) GetKind() ClaimKind {
	if m != nil {
		return m.Kind
	}
	return ClaimKind_CLAIM_KIND_UNSPECIFIED
}

func (m *Claim) GetStatus() ClaimStatus {
	if m != nil {
		return m.Status
	}
	return ClaimStatus_CLAIM_STATUS_NONE
}

func (m *Claim) GetNullifier() string {
	if m != nil {
		return m.Nullifier
	}
	return ""
}

func (m *Claim) GetWithdrawalId() string {
	if m != nil {
		return m.WithdrawalId
	}
	return ""
}

func (m *Claim) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Claim) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *Claim) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *Claim) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *Claim) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Claim) GetBatchNumber() uint64 {
	if m != nil {
		return m.BatchNumber
	}
	return 0
}

func (m *Claim) GetAnchor() string {
	if m != nil {
		return m.Anchor
	}
	return ""
}

func (m *Claim) GetAvailableAt() int64 {
	if m != nil {
		return m.AvailableAt
	}
	return 0
}

// Nullifier is the terminal replay guard of one withdrawal or exit.
type Nullifier struct {
	Nullifier    string          `protobuf:"bytes,1,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
	Status       NullifierStatus `protobuf:"varint,2,opt,name=status,proto3,enum=paxprotocol.paxchain.layerxcustody.NullifierStatus" json:"status,omitempty"`
	ClaimId      string          `protobuf:"bytes,3,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	WithdrawalId string          `protobuf:"bytes,4,opt,name=withdrawal_id,json=withdrawalId,proto3" json:"withdrawal_id,omitempty"`
}

func (m *Nullifier) Reset()         { *m = Nullifier{} }
func (m *Nullifier) String() string { return proto.CompactTextString(m) }
func (*Nullifier) ProtoMessage()    {}
func (*Nullifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_e53959e114ebead8, []int{4}
}
func (m *Nullifier) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Nullifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Nullifier.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Nullifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nullifier.Merge(m, src)
}
func (m *Nullifier) XXX_Size() int {
	return m.Size()
}
func (m *Nullifier) XXX_DiscardUnknown() {
	xxx_messageInfo_Nullifier.DiscardUnknown(m)
}

var xxx_messageInfo_Nullifier proto.InternalMessageInfo

func (m *Nullifier) GetNullifier() string {
	if m != nil {
		return m.Nullifier
	}
	return ""
}

func (m *Nullifier) GetStatus() NullifierStatus {
	if m != nil {
		return m.Status
	}
	return NullifierStatus_NULLIFIER_STATUS_NONE
}

func (m *Nullifier) GetClaimId() string {
	if m != nil {
		return m.ClaimId
	}
	return ""
}

func (m *Nullifier) GetWithdrawalId() string {
	if m != nil {
		return m.WithdrawalId
	}
	return ""
}

// Checkpoint is one finalized LayerX batch commitment.
type Checkpoint struct {
	BatchNumber uint64 `protobuf:"varint,1,opt,name=batch_number,json=batchNumber,proto3" json:"batch_number,omitempty"`
	StateRoot   string `protobuf:"bytes,2,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	ReceiptRoot string `protobuf:"bytes,3,opt,name=receipt_root,json=receiptRoot,proto3" json:"receipt_root,omitempty"`
	// finalized_at is the unix second the checkpoint was registered.
	FinalizedAt int64 `protobuf:"varint,4,opt,name=finalized_at,json=finalizedAt,proto3" json:"finalized_at,omitempty"`
}

func (m *Checkpoint) Reset()         { *m = Checkpoint{} }
func (m *Checkpoint) String() string { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()    {}
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_e53959e114ebead8, []int{5}
}
func (m *Checkpoint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Checkpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Checkpoint.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Checkpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkpoint.Merge(m, src)
}
func (m *Checkpoint) XXX_Size() int {
	return m.Size()
}
func (m *Checkpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Checkpoint proto.InternalMessageInfo

func (m *Checkpoint) GetBatchNumber() uint64 {
	if m != nil {
		return m.BatchNumber
	}
	return 0
}

func (m *Checkpoint) GetStateRoot() string {
	if m != nil {
		return m.StateRoot
	}
	return ""
}

func (m *Checkpoint) GetReceiptRoot() string {
	if m != nil {
		return m.ReceiptRoot
	}
	return ""
}

func (m *Checkpoint) GetFinalizedAt() int64 {
	if m != nil {
		return m.FinalizedAt
	}
	return 0
}

// ConsumedBalance marks an account balance already exited at an anchor.
type ConsumedBalance struct {
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	AssetId string `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Anchor  string `protobuf:"bytes,3,opt,name=anchor,proto3" json:"anchor,omitempty"`
}

func (m *ConsumedBalance) Reset()         { *m = ConsumedBalance{} }
func (m *ConsumedBalance) String() string { return proto.CompactTextString(m) }
func (*ConsumedBalance) ProtoMessage()    {}
func (*ConsumedBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_e53959e114ebead8, []int{6}
}
func (m *ConsumedBalance) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConsumedBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConsumedBalance.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConsumedBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumedBalance.Merge(m, src)
}
func (m *ConsumedBalance) XXX_Size() int {
	return m.Size()
}
func (m *ConsumedBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumedBalance.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumedBalance proto.InternalMessageInfo

func (m *ConsumedBalance) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ConsumedBalance) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *ConsumedBalance) GetAnchor() string {
	if m != nil {
		return m.Anchor
	}
	return ""
}

// AssetTotals is the custody accounting of one asset, in base units.
type AssetTotals struct {
	AssetId string `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// custodied is deposits minus paid releases: the outstanding liability.
	Custodied string `protobuf:"bytes,2,opt,name=custodied,proto3" json:"custodied,omitempty"`
	Released  string `protobuf:"bytes,3,opt,name=released,proto3" json:"released,omitempty"`
	// pending is the sum of queued, unpaid claims.
	Pending string `protobuf:"bytes,4,opt,name=pending,proto3" json:"pending,omitempty"`
}

func (m *AssetTotals) Reset()         { *m = AssetTotals{} }
func (m *AssetTotals) String() string { return proto.CompactTextString(m) }
func (*AssetTotals) ProtoMessage()    {}
func (*AssetTotals) Descriptor() ([]byte, []int) {
	return fileDescriptor_e53959e114ebead8, []int{7}
}
func (m *AssetTotals) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AssetTotals) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AssetTotals.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AssetTotals) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetTotals.Merge(m, src)
}
func (m *AssetTotals) XXX_Size() int {
	return m.Size()
}
func (m *AssetTotals) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetTotals.DiscardUnknown(m)
}

var xxx_messageInfo_AssetTotals proto.InternalMessageInfo

func (m *AssetTotals) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *AssetTotals) GetCustodied() string {
	if m != nil {
		return m.Custodied
	}
	return ""
}

func (m *AssetTotals) GetReleased() string {
	if m != nil {
		return m.Released
	}
	return ""
}

func (m *AssetTotals) GetPending() string {
	if m != nil {
		return m.Pending
	}
	return ""
}

func init() {
	proto.RegisterEnum("paxprotocol.paxchain.layerxcustody.ClaimKind", ClaimKind_name, ClaimKind_value)
	proto.RegisterEnum("paxprotocol.paxchain.layerxcustody.ClaimStatus", ClaimStatus_name, ClaimStatus_value)
	proto.RegisterEnum("paxprotocol.paxchain.layerxcustody.NullifierStatus", NullifierStatus_name, NullifierStatus_value)
	proto.RegisterType((*AssetMapping)(nil), "paxprotocol.paxchain.layerxcustody.AssetMapping")
	proto.RegisterType((*Deposit)(nil), "paxprotocol.paxchain.layerxcustody.Deposit")
	proto.RegisterType((*DepositNonce)(nil), "paxprotocol.paxchain.layerxcustody.DepositNonce")
	proto.RegisterType((*Claim)(nil), "paxprotocol.paxchain.layerxcustody.Claim")
	proto.RegisterType((*Nullifier)(nil), "paxprotocol.paxchain.layerxcustody.Nullifier")
	proto.RegisterType((*Checkpoint)(nil), "paxprotocol.paxchain.layerxcustody.Checkpoint")
	proto.RegisterType((*ConsumedBalance)(nil), "paxprotocol.paxchain.layerxcustody.ConsumedBalance")
	proto.RegisterType((*AssetTotals)(nil), "paxprotocol.paxchain.layerxcustody.AssetTotals")
}

func init() { proto.RegisterFile("layerxcustody/state.proto", fileDescriptor_e53959e114ebead8) }

var fileDescriptor_e53959e114ebead8 = []byte{
	// 955 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xd1, 0x4e, 0xe3, 0x46,
	0x14, 0xc5, 0x04, 0x92, 0xf8, 0x26, 0x0b, 0xa9, 0xb5, 0x8b, 0x0c, 0x82, 0x94, 0xa6, 0x0f, 0x45,
	0x48, 0x24, 0xd2, 0xee, 0x17, 0x18, 0xc7, 0xbb, 0xb5, 0x08, 0x06, 0x39, 0xa1, 0x5b, 0x55, 0xed,
	0x5a, 0x13, 0x7b, 0x20, 0x23, 0xec, 0x19, 0xd7, 0x1e, 0x97, 0x50, 0xf5, 0x0b, 0xfa, 0xd4, 0x87,
	0x7e, 0x4b, 0xbf, 0xa1, 0x8f, 0xbc, 0x54, 0xea, 0x63, 0x05, 0xdf, 0xd0, 0xf7, 0xca, 0x63, 0x27,
	0x76, 0x92, 0xd2, 0xee, 0x9b, 0xcf, 0x99, 0x7b, 0xef, 0xcc, 0xbd, 0xe7, 0xcc, 0xc8, 0xb0, 0xeb,
	0xa3, 0x7b, 0x1c, 0x4d, 0xdd, 0x24, 0xe6, 0xcc, 0xbb, 0xef, 0xc5, 0x1c, 0x71, 0xdc, 0x0d, 0x23,
	0xc6, 0x99, 0xd2, 0x09, 0xd1, 0x54, 0x7c, 0xb9, 0xcc, 0xef, 0x86, 0x68, 0xea, 0x4e, 0x10, 0xa1,
	0xdd, 0x85, 0xf8, 0xce, 0x1f, 0x12, 0x34, 0xb5, 0x38, 0xc6, 0xfc, 0x1c, 0x85, 0x21, 0xa1, 0x37,
	0xca, 0x2e, 0xd4, 0x51, 0x8a, 0x1d, 0xe2, 0xa9, 0xd2, 0xa1, 0x74, 0x24, 0xdb, 0x35, 0x81, 0x4d,
	0x4f, 0x79, 0x09, 0x9b, 0x1e, 0xa6, 0x2c, 0x50, 0xd7, 0x05, 0x9f, 0x01, 0x45, 0x85, 0x5a, 0xc8,
	0x08, 0xe5, 0x38, 0x52, 0x2b, 0x59, 0x7c, 0x0e, 0xd3, 0x15, 0x4c, 0xd1, 0xd8, 0xc7, 0x9e, 0xba,
	0x71, 0x28, 0x1d, 0xd5, 0xed, 0x19, 0x54, 0x76, 0xa0, 0x1a, 0xa2, 0x24, 0xc6, 0x9e, 0xba, 0x29,
	0x16, 0x72, 0xa4, 0x7c, 0x01, 0xdb, 0x01, 0xa1, 0x24, 0x48, 0x02, 0xc7, 0xc3, 0x21, 0x8b, 0x09,
	0x57, 0xab, 0xa2, 0xe6, 0x56, 0x4e, 0xf7, 0x33, 0x56, 0xf9, 0x14, 0x1a, 0x79, 0x07, 0x8e, 0x8b,
	0x42, 0xb5, 0x26, 0x82, 0x20, 0xa7, 0x74, 0x14, 0x76, 0xfe, 0x96, 0xa0, 0x36, 0x0b, 0x3e, 0x00,
	0xc8, 0xab, 0x15, 0x4d, 0xc9, 0x39, 0x93, 0xb5, 0x45, 0xa8, 0x87, 0xa7, 0xa2, 0xad, 0x0d, 0x3b,
	0x03, 0xca, 0x3e, 0xcc, 0x42, 0xd8, 0xac, 0xb1, 0x82, 0x50, 0x0e, 0xa1, 0x31, 0xc6, 0x14, 0x5f,
	0x13, 0x97, 0xa0, 0xe8, 0x5e, 0xb4, 0x27, 0xdb, 0x65, 0x6a, 0x61, 0x8e, 0x9b, 0xcf, 0xcc, 0xb1,
	0x5a, 0x9e, 0xe3, 0x0e, 0x54, 0x51, 0xc0, 0x12, 0xca, 0xf3, 0x6e, 0x72, 0x94, 0x46, 0x53, 0x46,
	0x5d, 0xac, 0xd6, 0xb3, 0xe3, 0x09, 0x90, 0x46, 0x4f, 0x30, 0xb9, 0x99, 0x70, 0x55, 0x3e, 0x94,
	0x8e, 0x2a, 0x76, 0x8e, 0x3a, 0xdf, 0x41, 0x33, 0x6f, 0xdb, 0x12, 0x71, 0x0b, 0x6d, 0x48, 0xcb,
	0x6d, 0x94, 0x0f, 0xb9, 0xbe, 0x72, 0xc8, 0x6c, 0xdb, 0x4a, 0x69, 0xdb, 0xce, 0x43, 0x05, 0x36,
	0x75, 0x1f, 0x91, 0x20, 0x4d, 0x75, 0xd3, 0x8f, 0x92, 0x4f, 0x04, 0x36, 0x3d, 0x45, 0x83, 0x8d,
	0x5b, 0x42, 0xb3, 0x8a, 0x5b, 0xaf, 0x4f, 0xba, 0xff, 0x6f, 0xc3, 0xae, 0xa8, 0x79, 0x46, 0xa8,
	0x67, 0x8b, 0x54, 0xe5, 0x1d, 0x54, 0x53, 0x27, 0x27, 0xb1, 0xd8, 0x7e, 0xeb, 0x75, 0xef, 0xa3,
	0x8b, 0x0c, 0x45, 0x9a, 0x9d, 0xa7, 0xa7, 0xfd, 0xd3, 0xc4, 0xf7, 0xc9, 0x35, 0xc1, 0x51, 0x2e,
	0x53, 0x41, 0x28, 0x9f, 0xc3, 0x8b, 0x3b, 0xc2, 0x27, 0x5e, 0x84, 0xee, 0x90, 0x5f, 0x28, 0xd5,
	0x2c, 0x48, 0xd3, 0x4b, 0x6d, 0x8c, 0x5c, 0x57, 0x28, 0x53, 0xcd, 0x67, 0x94, 0xc1, 0x85, 0xf1,
	0xd5, 0x9e, 0xd1, 0xb8, 0x5e, 0xd6, 0x78, 0x1f, 0xe4, 0x08, 0xbb, 0x24, 0x24, 0x98, 0x66, 0xc2,
	0xc9, 0x76, 0x41, 0x94, 0x1c, 0x00, 0x0b, 0x0e, 0xf8, 0x0c, 0x9a, 0x63, 0xc4, 0xdd, 0x89, 0x43,
	0x93, 0x60, 0x8c, 0x23, 0xb5, 0x21, 0x14, 0x69, 0x08, 0xce, 0x12, 0x94, 0x48, 0xa5, 0xee, 0x84,
	0x45, 0x6a, 0x33, 0x4f, 0x15, 0x28, 0x4d, 0x45, 0x3f, 0x20, 0xe2, 0xa7, 0xd7, 0xce, 0x41, 0x5c,
	0x7d, 0x21, 0xcc, 0xd2, 0x98, 0x73, 0x1a, 0xef, 0xfc, 0x26, 0x81, 0x6c, 0xcd, 0x27, 0xb2, 0x30,
	0x2f, 0x69, 0x79, 0x5e, 0x67, 0x73, 0x59, 0x32, 0x6d, 0xdf, 0x7c, 0x8c, 0x2c, 0xf3, 0xe2, 0x4b,
	0xd2, 0x94, 0x1d, 0x54, 0x59, 0x74, 0xd0, 0x8a, 0x2e, 0x1b, 0xab, 0xba, 0x74, 0x7e, 0x95, 0x00,
	0xf4, 0x09, 0x76, 0x6f, 0xc5, 0x7b, 0xb3, 0x32, 0x25, 0x69, 0x75, 0x4a, 0x07, 0x00, 0xe2, 0x7d,
	0x74, 0x22, 0xc6, 0x78, 0x6e, 0x78, 0x59, 0x30, 0x36, 0x63, 0xa2, 0x42, 0x84, 0x5d, 0x4c, 0x42,
	0x9e, 0x05, 0x64, 0x87, 0x6a, 0xe4, 0xdc, 0x2c, 0xe4, 0x9a, 0x50, 0xe4, 0x93, 0x1f, 0xb1, 0x97,
	0xce, 0x73, 0x23, 0x9b, 0xe7, 0x9c, 0xd3, 0x78, 0xe7, 0x03, 0x6c, 0xeb, 0x8c, 0xc6, 0x49, 0x80,
	0xbd, 0x53, 0xe4, 0xa3, 0xf4, 0x12, 0x96, 0x1c, 0x24, 0x3d, 0xef, 0xa0, 0xa5, 0x0b, 0x58, 0x48,
	0x5a, 0x29, 0x4b, 0xda, 0xf9, 0x09, 0x1a, 0xe2, 0xc1, 0x1e, 0x31, 0x8e, 0xfc, 0xf8, 0xbf, 0xde,
	0xeb, 0x7d, 0x90, 0x33, 0x0d, 0x08, 0x9e, 0x55, 0x2f, 0x08, 0x65, 0x0f, 0xea, 0x11, 0xf6, 0x31,
	0x4a, 0x5f, 0xe1, 0x6c, 0x87, 0x39, 0x16, 0x6f, 0x3a, 0xa6, 0x1e, 0xa1, 0x37, 0xf9, 0xe4, 0x67,
	0xf0, 0xf8, 0x03, 0xc8, 0xf3, 0xbb, 0xaa, 0xec, 0xc1, 0x8e, 0x3e, 0xd0, 0xcc, 0x73, 0xe7, 0xcc,
	0xb4, 0xfa, 0xce, 0x95, 0x35, 0xbc, 0x34, 0x74, 0xf3, 0xad, 0x69, 0xf4, 0x5b, 0x6b, 0xca, 0x2e,
	0xbc, 0x2a, 0xad, 0xbd, 0x37, 0x47, 0x5f, 0xf6, 0x6d, 0xed, 0xbd, 0x36, 0x68, 0x49, 0x4b, 0x69,
	0x6f, 0x2f, 0x6c, 0xdd, 0xe8, 0x3b, 0xc6, 0xd7, 0xe6, 0xa8, 0xb5, 0x7e, 0xfc, 0x3d, 0x34, 0x4a,
	0xd7, 0x58, 0x79, 0x05, 0x9f, 0x64, 0xa1, 0xc3, 0x91, 0x36, 0xba, 0x1a, 0x3a, 0xd6, 0x85, 0x65,
	0xb4, 0xd6, 0x14, 0x15, 0x5e, 0x2e, 0xd0, 0x97, 0x86, 0xd5, 0x37, 0xad, 0x77, 0x2d, 0x69, 0x25,
	0xe1, 0x52, 0x33, 0xfb, 0xad, 0xf5, 0x62, 0xcb, 0x9c, 0xd6, 0x35, 0x4b, 0x37, 0x06, 0x03, 0xa3,
	0xdf, 0xaa, 0x1c, 0xff, 0x2c, 0xc1, 0xf6, 0x92, 0x47, 0xd3, 0xd3, 0x5b, 0x57, 0x83, 0x41, 0xda,
	0x8c, 0xbd, 0xb4, 0xf7, 0x01, 0xec, 0xae, 0x2c, 0xd9, 0xc6, 0xd0, 0xb0, 0xbf, 0x32, 0xfa, 0x2d,
	0xe9, 0x5f, 0x97, 0xf5, 0x0b, 0x6b, 0x78, 0x75, 0x6e, 0xa4, 0x07, 0x69, 0xc3, 0xde, 0xea, 0x72,
	0x71, 0x98, 0xd3, 0x6f, 0x7f, 0x7f, 0x6c, 0x4b, 0x0f, 0x8f, 0x6d, 0xe9, 0xaf, 0xc7, 0xb6, 0xf4,
	0xcb, 0x53, 0x7b, 0xed, 0xe1, 0xa9, 0xbd, 0xf6, 0xe7, 0x53, 0x7b, 0xed, 0x9b, 0xd3, 0x1b, 0xc2,
	0x27, 0xc9, 0xb8, 0xeb, 0xb2, 0xa0, 0x17, 0x13, 0x8f, 0xb0, 0x08, 0x9d, 0xf8, 0x68, 0x1c, 0xf7,
	0x42, 0x34, 0xc5, 0x38, 0x3a, 0xa1, 0x98, 0xdf, 0xb1, 0xe8, 0xb6, 0x17, 0x30, 0x2f, 0xf1, 0x71,
	0xdc, 0x5b, 0xfc, 0x2f, 0xe0, 0xf7, 0x21, 0x8e, 0xc7, 0x55, 0x71, 0x57, 0xdf, 0xfc, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x1f, 0x72, 0xcf, 0x5a, 0x35, 0x08, 0x00, 0x00,
}

func (m *AssetMapping) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AssetMapping) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AssetMapping) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CustodyCap) > 0 {
		i -= len(m.CustodyCap)
		copy(dAtA[i:], m.CustodyCap)
		i = encodeVarintState(dAtA, i, uint64(len(m.CustodyCap)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.MinimumDeposit) > 0 {
		i -= len(m.MinimumDeposit)
		copy(dAtA[i:], m.MinimumDeposit)
		i = encodeVarintState(dAtA, i, uint64(len(m.MinimumDeposit)))
		i--
		dAtA[i] = 0x32
	}
	if m.Paused {
		i--
		if m.Paused {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.Pointer) > 0 {
		i -= len(m.Pointer)
		copy(dAtA[i:], m.Pointer)
		i = encodeVarintState(dAtA, i, uint64(len(m.Pointer)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintState(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AssetId) > 0 {
		i -= len(m.AssetId)
		copy(dAtA[i:], m.AssetId)
		i = encodeVarintState(dAtA, i, uint64(len(m.AssetId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Deposit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Deposit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Deposit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x48
	}
	if m.Nonce != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x40
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintState(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintState(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.AssetId) > 0 {
		i -= len(m.AssetId)
		copy(dAtA[i:], m.AssetId)
		i = encodeVarintState(dAtA, i, uint64(len(m.AssetId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Beneficiary) > 0 {
		i -= len(m.Beneficiary)
		copy(dAtA[i:], m.Beneficiary)
		i = encodeVarintState(dAtA, i, uint64(len(m.Beneficiary)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Depositor) > 0 {
		i -= len(m.Depositor)
		copy(dAtA[i:], m.Depositor)
		i = encodeVarintState(dAtA, i, uint64(len(m.Depositor)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Index != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x10
	}
	if len(m.DepositId) > 0 {
		i -= len(m.DepositId)
		copy(dAtA[i:], m.DepositId)
		i = encodeVarintState(dAtA, i, uint64(len(m.DepositId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DepositNonce) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DepositNonce) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DepositNonce) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Nonce != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x18
	}
	if len(m.AssetId) > 0 {
		i -= len(m.AssetId)
		copy(dAtA[i:], m.AssetId)
		i = encodeVarintState(dAtA, i, uint64(len(m.AssetId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Depositor) > 0 {
		i -= len(m.Depositor)
		copy(dAtA[i:], m.Depositor)
		i = encodeVarintState(dAtA, i, uint64(len(m.Depositor)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Claim) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Claim) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Claim) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AvailableAt != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.AvailableAt))
		i--
		dAtA[i] = 0x68
	}
	if len(m.Anchor) > 0 {
		i -= len(m.Anchor)
		copy(dAtA[i:], m.Anchor)
		i = encodeVarintState(dAtA, i, uint64(len(m.Anchor)))
		i--
		dAtA[i] = 0x62
	}
	if m.BatchNumber != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.BatchNumber))
		i--
		dAtA[i] = 0x58
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintState(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintState(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintState(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.AssetId) > 0 {
		i -= len(m.AssetId)
		copy(dAtA[i:], m.AssetId)
		i = encodeVarintState(dAtA, i, uint64(len(m.AssetId)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintState(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.WithdrawalId) > 0 {
		i -= len(m.WithdrawalId)
		copy(dAtA[i:], m.WithdrawalId)
		i = encodeVarintState(dAtA, i, uint64(len(m.WithdrawalId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Nullifier) > 0 {
		i -= len(m.Nullifier)
		copy(dAtA[i:], m.Nullifier)
		i = encodeVarintState(dAtA, i, uint64(len(m.Nullifier)))
		i--
		dAtA[i] = 0x22
	}
	if m.Status != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x18
	}
	if m.Kind != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Kind))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ClaimId) > 0 {
		i -= len(m.ClaimId)
		copy(dAtA[i:], m.ClaimId)
		i = encodeVarintState(dAtA, i, uint64(len(m.ClaimId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Nullifier) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Nullifier) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Nullifier) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WithdrawalId) > 0 {
		i -= len(m.WithdrawalId)
		copy(dAtA[i:], m.WithdrawalId)
		i = encodeVarintState(dAtA, i, uint64(len(m.WithdrawalId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ClaimId) > 0 {
		i -= len(m.ClaimId)
		copy(dAtA[i:], m.ClaimId)
		i = encodeVarintState(dAtA, i, uint64(len(m.ClaimId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Status != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Nullifier) > 0 {
		i -= len(m.Nullifier)
		copy(dAtA[i:], m.Nullifier)
		i = encodeVarintState(dAtA, i, uint64(len(m.Nullifier)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Checkpoint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Checkpoint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Checkpoint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FinalizedAt != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.FinalizedAt))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ReceiptRoot) > 0 {
		i -= len(m.ReceiptRoot)
		copy(dAtA[i:], m.ReceiptRoot)
		i = encodeVarintState(dAtA, i, uint64(len(m.ReceiptRoot)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.StateRoot) > 0 {
		i -= len(m.StateRoot)
		copy(dAtA[i:], m.StateRoot)
		i = encodeVarintState(dAtA, i, uint64(len(m.StateRoot)))
		i--
		dAtA[i] = 0x12
	}
	if m.BatchNumber != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.BatchNumber))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ConsumedBalance) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConsumedBalance) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsumedBalance) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Anchor) > 0 {
		i -= len(m.Anchor)
		copy(dAtA[i:], m.Anchor)
		i = encodeVarintState(dAtA, i, uint64(len(m.Anchor)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AssetId) > 0 {
		i -= len(m.AssetId)
		copy(dAtA[i:], m.AssetId)
		i = encodeVarintState(dAtA, i, uint64(len(m.AssetId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintState(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AssetTotals) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AssetTotals) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AssetTotals) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Pending) > 0 {
		i -= len(m.Pending)
		copy(dAtA[i:], m.Pending)
		i = encodeVarintState(dAtA, i, uint64(len(m.Pending)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Released) > 0 {
		i -= len(m.Released)
		copy(dAtA[i:], m.Released)
		i = encodeVarintState(dAtA, i, uint64(len(m.Released)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Custodied) > 0 {
		i -= len(m.Custodied)
		copy(dAtA[i:], m.Custodied)
		i = encodeVarintState(dAtA, i, uint64(len(m.Custodied)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AssetId) > 0 {
		i -= len(m.AssetId)
		copy(dAtA[i:], m.AssetId)
		i = encodeVarintState(dAtA, i, uint64(len(m.AssetId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintState(dAtA []byte, offset int, v uint64) int {
	offset -= sovState(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AssetMapping) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AssetId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Pointer)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.Enabled {
		n += 2
	}
	if m.Paused {
		n += 2
	}
	l = len(m.MinimumDeposit)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.CustodyCap)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	return n
}

func (m *Deposit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DepositId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.Index != 0 {
		n += 1 + sovState(uint64(m.Index))
	}
	l = len(m.Depositor)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Beneficiary)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.AssetId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.Nonce != 0 {
		n += 1 + sovState(uint64(m.Nonce))
	}
	if m.Height != 0 {
		n += 1 + sovState(uint64(m.Height))
	}
	return n
}

func (m *DepositNonce) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Depositor)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.AssetId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.Nonce != 0 {
		n += 1 + sovState(uint64(m.Nonce))
	}
	return n
}

func (m *Claim) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClaimId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.Kind != 0 {
		n += 1 + sovState(uint64(m.Kind))
	}
	if m.Status != 0 {
		n += 1 + sovState(uint64(m.Status))
	}
	l = len(m.Nullifier)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.WithdrawalId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.AssetId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.BatchNumber != 0 {
		n += 1 + sovState(uint64(m.BatchNumber))
	}
	l = len(m.Anchor)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.AvailableAt != 0 {
		n += 1 + sovState(uint64(m.AvailableAt))
	}
	return n
}

func (m *Nullifier) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Nullifier)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovState(uint64(m.Status))
	}
	l = len(m.ClaimId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.WithdrawalId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	return n
}

func (m *Checkpoint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BatchNumber != 0 {
		n += 1 + sovState(uint64(m.BatchNumber))
	}
	l = len(m.StateRoot)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.ReceiptRoot)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.FinalizedAt != 0 {
		n += 1 + sovState(uint64(m.FinalizedAt))
	}
	return n
}

func (m *ConsumedBalance) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.AssetId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Anchor)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	return n
}

func (m *AssetTotals) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AssetId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Custodied)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Released)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Pending)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	return n
}

func sovState(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozState(x uint64) (n int) {
	return sovState(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AssetMapping) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AssetMapping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AssetMapping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pointer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pointer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Paused", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Paused = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumDeposit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinimumDeposit = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustodyCap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CustodyCap = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Deposit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Deposit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Deposit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Depositor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Depositor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Beneficiary", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Beneficiary = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DepositNonce) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DepositNonce: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DepositNonce: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Depositor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Depositor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Claim) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Claim: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Claim: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClaimId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			m.Kind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Kind |= ClaimKind(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= ClaimStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nullifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nullifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawalId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchNumber", wireType)
			}
			m.BatchNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BatchNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Anchor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Anchor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailableAt", wireType)
			}
			m.AvailableAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AvailableAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Nullifier) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Nullifier: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Nullifier: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nullifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nullifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= NullifierStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClaimId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawalId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Checkpoint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Checkpoint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Checkpoint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchNumber", wireType)
			}
			m.BatchNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BatchNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateRoot", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateRoot = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiptRoot", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReceiptRoot = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizedAt", wireType)
			}
			m.FinalizedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FinalizedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConsumedBalance) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConsumedBalance: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConsumedBalance: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Anchor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Anchor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AssetTotals) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AssetTotals: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AssetTotals: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Custodied", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Custodied = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Released", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Released = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pending", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pending = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipState(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowState
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthState
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupState
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthState
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthState        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowState          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupState = fmt.Errorf("proto: unexpected end of group")
)
