package types

const (
	EventCheckpointSubmitted = "layerx_checkpoint_submitted"
	EventCheckpointFinalized = "layerx_checkpoint_finalized"
	EventAvailability        = "layerx_availability_attested"
	EventGuarantorRegistered = "layerx_guarantor_registered"
	EventGuarantorActivated  = "layerx_guarantor_activated"
	EventBondIncreased       = "layerx_guarantor_bond_increased"
	EventUnbondBegun         = "layerx_guarantor_unbond_begun"
	EventUnbondCompleted     = "layerx_guarantor_unbond_completed"
	EventGuarantorSlashed    = "layerx_guarantor_slashed"
	EventChallengeOpened     = "layerx_challenge_opened"
	EventChallengeResolved   = "layerx_challenge_resolved"
	EventSequencerAuthorized = "layerx_sequencer_authorized"
	EventParamsUpdated       = "layerx_anchor_params_updated"

	AttributeBatchNumber  = "batch_number"
	AttributeCheckpointID = "checkpoint_id"
	AttributeStateRoot    = "state_root"
	AttributeReceiptRoot  = "receipt_root"
	AttributeSigners      = "signers"
	AttributeGuarantorID  = "guarantor_id"
	AttributeSigner       = "signer"
	AttributeOperator     = "operator"
	AttributeAmount       = "amount"
	AttributeCompletion   = "completion_time"
	AttributeReason       = "reason"
	AttributeReporter     = "reporter"
	AttributeReward       = "reporter_reward"
	AttributeChallengeID  = "challenge_id"
	AttributeKind         = "kind"
	AttributeUpheld       = "upheld"
	AttributeClassMask    = "class_mask"
	AttributeSequencerID  = "sequencer_id"
	AttributeFirstBatch   = "first_batch_number"
	AttributeLastBatch    = "last_batch_number"
)
