[package]
name = "layerx-solana-mirror-program"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[workspace]

[lib]
crate-type = ["cdylib", "lib"]

[features]
custom-heap = []
custom-panic = []

[dependencies]
solana-program = "=2.3.0"
solana-system-interface = { version = "=1.0.0", features = ["bincode"] }
solana-sdk-ids = "=2.2.1"
zeroize = "=1.8.1"
sha2 = { version = "=0.10.9", features = ["compress"] }

[dev-dependencies]
solana-program-test = "=2.3.13"
solana-sdk = "=2.3.1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[lints.rust]
unsafe_code = "deny"
unexpected_cfgs = { level = "deny", check-cfg = ['cfg(target_os, values("solana"))'] }
