package types

const (
	EventRequested         = "XWebRequested"
	EventFulfilled         = "XWebFulfilled"
	EventRefunded          = "XWebRefunded"
	EventCallback          = "xweb_callback"
	EventAttestorAdded     = "xweb_attestor_registered"
	EventAttestorRemoved   = "xweb_attestor_removed"
	EventThresholdSet      = "xweb_threshold_set"
	EventParamsSet         = "xweb_params_set"
	EventPaused            = "xweb_paused"
	EventUnpaused          = "xweb_unpaused"
	AttributeRequestID     = "request_id"
	AttributeRequester     = "requester"
	AttributeOrigin        = "origin"
	AttributeNetworkID     = "network_id"
	AttributeKind          = "kind"
	AttributePayload       = "payload"
	AttributePayloadHash   = "payload_hash"
	AttributeCallbackGas   = "callback_gas"
	AttributeFee           = "fee"
	AttributeHeight        = "height"
	AttributeTimeoutHeight = "timeout_height"
	AttributeContentDigest = "content_digest"
	AttributeResponseHash  = "response_hash"
	AttributeFullLength    = "full_length"
	AttributeSigners       = "signers"
	AttributeOutcome       = "outcome"
	AttributeGasUsed       = "gas_used"
	AttributeSigner        = "signer"
	AttributePayout        = "payout"
	AttributeThreshold     = "threshold"
	AttributePayloadCap    = "max_payload_bytes"
	AttributeCallbackCap   = "max_callback_gas"
	AttributeTimeoutBlocks = "timeout_blocks"
)
