package types

const (
	EventTypeMarketCreated      = "launchpad_market_created"
	EventTypeSwap               = "launchpad_swap"
	EventTypeFeeRecorded        = "launchpad_fee_recorded"
	EventTypeFeeStrategyChanged = "launchpad_fee_strategy_changed"
	EventTypeFeesClaimed        = "launchpad_fees_claimed"
	EventTypeFeesBurned         = "launchpad_fees_burned"
	EventTypeAirdropTriggered   = "launchpad_airdrop_triggered"
	EventTypeAirdropClaimed     = "launchpad_airdrop_claimed"
	EventTypeLpRewardsSent      = "launchpad_lp_rewards_sent"
	EventTypePauseToggled       = "launchpad_pause_toggled"
	EventTypeParamsUpdated      = "launchpad_params_updated"

	AttributeKeyDenom       = "denom"
	AttributeKeyPointer     = "pointer"
	AttributeKeyCreator     = "creator"
	AttributeKeyTrader      = "trader"
	AttributeKeyRecipient   = "recipient"
	AttributeKeyHolder      = "holder"
	AttributeKeyIsBuy       = "is_buy"
	AttributeKeyAmountIn    = "amount_in"
	AttributeKeyAmountOut   = "amount_out"
	AttributeKeyFee         = "fee"
	AttributeKeyFeeBps      = "fee_bps"
	AttributeKeyPrice       = "price"
	AttributeKeyProtocolCut = "protocol_cut"
	AttributeKeyPoolCut     = "pool_cut"
	AttributeKeyAmount      = "amount"
	AttributeKeyEpoch       = "epoch"
	AttributeKeyStrategy    = "strategy"
	AttributeKeyPaused      = "paused"
)
